Platform: invoking functions
nuclio/nuclio-sdk-go pull request #6
Opened 2018-08-18 10:25 UTC by makrusak

2018-08-19 03:17 UTC, pavius requested changes

2018-08-19 03:17 UTC, pavius commented on platform.go
> +	CallFunction(name string, event FunctionCallEvent) (Response, error)
Why not just use `Event`?

2018-08-19 03:17 UTC, pavius commented on platform.go
> +type BasicFunctionCallEvent struct {
Regardless of whether we need this - we call the "Basic" things "Abstract". Neither is more correct, but prefer consistency.

2018-08-19 03:17 UTC, pavius commented on platform.go
> +/*
I think I prefer the actual platform implementation (the one you PR'd to nuclio/nuclio) to reside here. The reason is that the SDK itself can be (and is) used as a standalone entity during testing. It would be helpful to have the ability to communicate between functions via HTTP when doing unit tests (this is how it is in Python).

2018-08-22 13:07 UTC, pavius approved these changes

2019-04-16 13:01 UTC, liranbg commented
continued on https://github.com/nuclio/nuclio-sdk-go/pull/11

2019-04-16 13:01 UTC, pavius commented
Merged through #11. Thanks for the contribution!

2019-04-16 13:01 UTC, closed without merging